Config = Config or {}

Config.RequiredCops = 0
Config.Price = {["D"] = 2, ["C"] = 5, ["B"] = 10, ["A"] = 25, ["S"] = 50} -- payment needed to start
Config.Payment = {["D"] = 4, ["C"] = 9, ["B"] = 18, ["A"] = 45, ["S"] = 80} -- pay they get when delivering
Config.OneTimeClasses = {"S", } -- car class which only has 1 contract per serverrestart

Config.Shops = {
    {vector3(-1359.19, -759.38, 22.3), "dgtablet"},
    {vector3(150.45, 318.74, 112.14), "trackerdisabler"},
}

Config.Locations = {
    {
        vector4(222.04, -783.99, 30.77, 67.0),
        vector4(225.52, -777.23, 30.77, 250.0),
    },
    {
        vector4(234.37, -800.08, 30.49, 67.0),
        vector4(238.59, -791.39, 30.51, 250.0),
    },
}

Config.DeliveryLocations = {
    vector3(-1154.81, -2035.22, 13.16),
    vector3(735.65, -1072.18, 22.23),
    vector3(1131.3, -793.24, 57.61),
    vector3(-324.86, -140.02, 39.01),
    vector3(1182.2, 2630.74, 37.82),
    vector3(751.47, -666.93, 27.79),
    vector3(264.25, -1785.49, 27.11),
    vector3(471.22, -1874.84, 26.87),
    vector3(-1375.76, -322.34, 39.6),
    vector3(-1391.99, -470.26, 31.59),
    vector3(756.45, -3195.37, 6.07),
    vector3(1202.19, -3117.09, 5.54),
    vector3(1507.5, -2136.57, 76.51),
    vector3(811.76, -117.26, 80.34),
    vector3(-1228.42, -1232.53, 7.04),
    vector3(156.78, -1692.49, 29.45),
    vector3(1235.98, -454.64, 66.68),
    vector3(2522.25, 4091.7, 38.62),
}

Config.Cars = {
    ["D"] = {
        {"Dinka Blista", "blista"},
        {"Karin Dilettante", "dilettante"},
        {"Weeny Issi", "issi2"},
        {"Bollokan Prairie", "prairie"},
        {"Maxwell Asbo", "asbo"},
        {"Blista Kanjo", "kanjo"},
        {"BF Club", "club"},
        {"Albany Buccaneer", "buccaneer"},
        {"Vapid Dominator", "dominator"},
        {"Imponte Phoenix", "phoenix"},
        {"Declasse Sabre Turbo", "sabregt"},
        {"Declasse Voodoo", "voodoo"},
        {"Imponte Dukes", "dukes"},
        {"Vapid Chino", "chino"},
        {"Willard Faction", "faction"},
        {"Declasse Moonbeam", "moonbeam"},
        {"Declasse Tampa", "tampa"},
        {"Vapid Ellie", "ellie"},
        {"Vapid Dominator GTT", "dominator7"},
    },
    ["C"] = {
        {"Dewbauchee Exemplar", "exemplar"},
        {"Ocelot F620", "f620"},
        {"Lampadati Felon GT", "felon2"},
        {"Ubermacht Sentinel", "sentinel"},
        {"Karin Asterope", "asterope"},
        {"Vulcar Ingot", "ingot"},
        {"Declasse Premier", "premier"},
        {"Obey Tailgater", "tailgater"},
        {"Enus Windsor", "windsor"},
        {"Karin Previon", "previon"},
    },
    ["B"] = {
        {"Gallivanter Baller", "baller"},
        {"Karin BeeJay XL", "bjxl"},
        {"Albany Cavalcade", "cavalcade"},
        {"Fathom FQ2", "fq2"},
        {"Emperor Habanero", "habanero"},
        {"Obey Rocoto", "rocoto"},
        {"Enus Huntley S", "huntley"},
        {"Pegassi Toros", "toros"},
        {"Ubermacht Rebla GTS", "rebla"},
    },
    ["A"] = {
        {"Maibatsu Penumbra", "penumbra2"},
        {"Karin Sultan", "sultan"},
        {"Benefactor Surano", "surano"},
        {"Dinka Jester", "jester"},
        {"Lampadati Furore GT", "furoregt"},
        {"Karin Kuruma", "kuruma"},
        {"Bravado Verlierer", "verlierer2"},
        {"Dewbauchee Specter", "specter"},
        {"Ocelot Pariah", "pariah"},
        {"Coil Raiden", "raiden"},
        {"Pfister Neon", "neon"},
        {"Ubermacht Revolter", "revolter"},
        {"Pfister Comet SR", "comet2"},
        {"Vapid Flash GT", "flashgt"},
        {"Grotti Itali GTO", "italigto"},
        {"Benefactor Schlagen GT", "schlagen"},
        {"Enus Paragon R", "paragon"},
        {"Obey 8F Drafter", "drafter"},
        {"Overflod Imorgon", "imorgon"},
        {"Ocelot Jugular", "jugular"},
        {"Karin Sultan Classic", "sultan3"},
        {"Grotti Itali RSX", "italirsx"},
    },
    ["S"] = {
        {"Truffade Adder", "adder"},
        {"Vapid Bullet", "bullet"},
        {"Grotti Cheetah", "cheetah"},
        {"Overflod Entity XF", "entityxr"},
        {"Pegassi Vacca", "vacca"},
        {"Coil Voltic", "voltic"},
        {"Pegassi Zentorno", "zentorno"},
        {"Progen", "T20"},
        {"Vapid FMJ", "fmj"},
        {"Pfister 811", "pfister811"},
        {"Ocelot Penetrator", "penetrator"},
        {"Pegassi Reaper", "reaper"},
        {"Progen Itali GTB", "italigtb"},
        {"Progen GP1", "gp1"},
        {"Dewbauchee Vagner", "vagner"},
        {"Grotti Visione", "visione"},
        {"Coil Cyclone", "cyclone"},
        {"Cheval Taipan", "taipan"},
        {"Truffade Thrax", "thrax"},
        {"Benefactor Krieger", "krieger"},
        {"Pegassi Zorrusso", "zorrusso"},
        {"Grotti Furia", "furia"},
    },
}